### ISSUE TITLE
[BUG] Wrong data for some tokens

### ISSUE THREAD

**Issue by dskarasev** [diegomanuel/binance-to-google-sheets#29] opened 2021-03-15 18:31 UTC
Hi, Diego!

The error didn't go away. The command " =BINANCE ("account"; "";) "shows the balances correctly, but the code from the dashboard example" =BINANCE ("prices"; A10:A; " ticker: "&B8&", prices: true")" does not recognize the correct price of most tokens. For example for the following tokens the price is not displayed at all:
MFT
PHA
PROM
RSR
RVN
TRB
USDT
XEM

For other tokens, for example, the FXS price is displayed incorrectly.
I think the problem is that the names of tokens are used instead of unique identifiers.

**Comment by ziggetty** [comment] 2021-03-16 10:30
Hi,

i can confirm that something strange happens. 

i tried to recreate this issue, and to me it seems it is not related to a specific token.
for some i get a price, for another a wrong one or no price at all.

so certainly something diego should look into
(or by accident ;-) already corrected)

but personally i do not use the function in such a way
i only get in a sheet all the prices in 1 go, and when i need them in another sheet
i will do a lookup.

the only nuisance i have is that (because of errors??) sometimes prices come from cache.
i would prefer if i could ignore cache, and get prices(new) or not(when errors)

**Comment by dskarasev** [comment] 2021-03-17 10:45
It doesn't look like cache because of price levels. FXS for example never had prices bellow 0.0

**Comment by ziggetty** [comment] 2021-03-17 13:50
i think i know what happens.

when a coin in your A10:A range is not traded against USDT, he does not find a price
and everything shifts

![afbeelding](https://user-images.githubusercontent.com/79652361/111477633-9badbf80-872f-11eb-84c6-1f951afd6915.png)

in column D i just get the price of the coin in the corresponding A cell as follows
![afbeelding](https://user-images.githubusercontent.com/79652361/111477882-d7e12000-872f-11eb-912a-699beff69921.png)

you now clearly can see how it shifts

also FXS only trades against BUSD or BTC

i think you can workaround it, but diego should certainly look into this.

**Comment by diegomanuel** [comment] 2021-03-18 00:09
Hey thanks @dskarasev for the report and thanks @ziggetty to corretly find out the problem!
It was an intended behaviour but it end up confusing instead of simplifying, so I removed it.
The fix is just on `master` branch for now, it will be included in the next release soon.

Thanks again, cheers! :beers:

**Closed by diegomanuel** 2021-03-18 00:09 UTC
Labels: bug
